name: aas2021
channels:
  - conda-forge
  - defaults
dependencies:
  - aioftp=0.18.1=pyhd8ed1ab_0
  - aiohttp=3.7.4=py39h89e85a6_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - astropy=4.2.1=py39hc89836e_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - blosc=1.21.0=he49afe7_0
  - brotli=1.0.9=h046ec9c_4
  - brotlipy=0.7.0=py39hcbf5805_1001
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.1=h0d85af4_1
  - ca-certificates=2020.12.5=h033912b_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2020.12.5=py39h6e9494a_1
  - cffi=1.14.5=py39h319c39b_0
  - chardet=4.0.0=py39h6e9494a_1
  - charls=2.2.0=h046ec9c_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.4.7=py39ha2c9959_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py39hcbf5805_3
  - dask-core=2021.5.0=pyhd8ed1ab_0
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - drms=0.6.2=pyhd8ed1ab_0
  - freetype=2.10.4=h4cff582_1
  - fsspec=2021.5.0=pyhd8ed1ab_0
  - giflib=5.2.1=hbcb3906_2
  - glymur=0.9.3=pyhd8ed1ab_0
  - greenlet=1.1.0=py39h9fcab8e_0
  - h5netcdf=0.11.0=pyhd8ed1ab_0
  - h5py=3.2.1=nompi_py39h1bb8402_100
  - hdf5=1.10.6=nompi_hc5d9132_1114
  - icu=68.1=h74dc148_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.3.31=py39hc392247_1
  - imageio=2.9.0=py_0
  - isodate=0.6.0=py_1
  - jbig=2.1=h0d85af4_2003
  - jpeg=9d=hbcb3906_0
  - jxrlib=1.1=h35c211d_2
  - kiwisolver=1.3.1=py39hedf5dff_1
  - krb5=1.19.1=hcfbf3a7_0
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libaec=1.0.4=h046ec9c_1
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcurl=7.76.1=hf45b732_2
  - libcxx=11.1.0=habf9029_0
  - libdeflate=1.7=h35c211d_5
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_22
  - libgfortran5=9.3.0=h6c81a4c_22
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=9_openblas
  - libnghttp2=1.43.0=h07e645a_0
  - libopenblas=0.3.15=openmp_h5e1b9a4_1
  - libpng=1.6.37=h7cec526_2
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.3.0=h1167814_1
  - libwebp-base=1.2.0=h0d85af4_2
  - libxml2=2.9.12=h93ec3fd_0
  - libxslt=1.1.33=h5739fc3_2
  - libzopfli=1.0.3=h046ec9c_0
  - llvm-openmp=11.1.0=hda6cdc1_1
  - locket=0.2.0=py_2
  - lxml=4.6.3=py39hf41e7f8_0
  - lz4-c=1.9.3=h046ec9c_0
  - matplotlib-base=3.4.2=py39hb07454d_0
  - multidict=5.1.0=py39hcbf5805_1
  - ncurses=6.2=h2e338ed_4
  - networkx=2.3=py_0
  - numpy=1.20.3=py39h7eed0ac_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1k=h0d85af4_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py39h4d6be9b_0
  - parfive=1.3.0=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pillow=8.2.0=py39h5fdd921_1
  - pip=21.1.2=pyhd8ed1ab_0
  - pooch=1.3.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyerfa=1.7.2=py39h4b0b724_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py39h6e9494a_3
  - python=3.9.4=h9133fd0_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py39hae3b40e_3
  - pyyaml=5.4.1=py39hcbf5805_0
  - readline=8.1=h05e3726_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-file=1.5.1=pyh9f0ad1d_0
  - requests-toolbelt=0.9.1=py_0
  - scikit-image=0.18.1=py39h089d6f7_0
  - scipy=1.6.3=py39h056f1c0_0
  - setuptools=49.6.0=py39h6e9494a_3
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=hb1e8313_3
  - soupsieve=2.0.1=py_1
  - sqlalchemy=1.4.15=py39h89e85a6_0
  - sqlite=3.35.5=h44b9ce1_0
  - sunpy=3.0.0=py39hc89836e_0
  - tifffile=2021.4.8=pyhd8ed1ab_0
  - tk=8.6.10=h0419947_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py39hcbf5805_1
  - tqdm=4.61.0=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - tzdata=2021a=he74cb21_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=haf1e3a3_0
  - yarl=1.6.3=py39hcbf5805_1
  - zeep=4.0.0=pyh9f0ad1d_0
  - zfp=0.5.5=he49afe7_5
  - zlib=1.2.11=h7795811_1010
  - zstd=1.5.0=h582d3a0_0
